import {
  pgTable,
  pgEnum,
  uuid,
  varchar,
  text,
  integer,
  bigint,
  jsonb,
  timestamp,
  uniqueIndex,
  index,
  check,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { organizations } from "./organizations.js";
import { users } from "./users.js";

/**
 * Milestone 6 — Revenue Intelligence.
 *
 * A `revenue_opportunities` row is the PERSISTED OUTPUT of a deterministic
 * backend calculation (see modules/revenue/*.ts) — never something an AI
 * model writes directly. The AI layer only ever reads a row (to explain
 * it) or triggers a status transition through the approval routes, which
 * re-validate everything server-side before writing here.
 *
 * Every numeric field (score, confidence, estimatedRevenueImpact) is
 * produced by revenue.engine.ts's documented, reproducible formula —
 * never by an LLM (see that module's header comment for the formula).
 */
export const revenueOpportunityTypeEnum = pgEnum("revenue_opportunity_type", [
  "CROSS_SELL",
  "UPSELL",
  "PAYMENT_RECOVERY",
  "ABANDONED_CHECKOUT",
  "REVENUE_DROP",
]);

export const revenueOpportunityStatusEnum = pgEnum("revenue_opportunity_status", [
  "OPEN",
  "APPROVED",
  "REJECTED",
  "EXECUTING",
  "EXECUTED",
  "FAILED",
  "EXPIRED",
]);

export const revenueOpportunitySeverityEnum = pgEnum("revenue_opportunity_severity", [
  "LOW",
  "MEDIUM",
  "HIGH",
  "CRITICAL",
]);

export const revenueOpportunities = pgTable(
  "revenue_opportunities",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    type: revenueOpportunityTypeEnum("type").notNull(),
    // Deterministic identity for this opportunity within its type — e.g.
    // "CROSS_SELL:<productAId>:<productBId>" or "REVENUE_DROP:<periodEnd>".
    // Lets the detection engine be safely re-run on a schedule/on-demand:
    // re-detecting the SAME underlying pattern updates this row (fresh
    // evidence/score) via ON CONFLICT DO UPDATE instead of creating a
    // duplicate open opportunity every time it runs.
    dedupeKey: varchar("dedupe_key", { length: 320 }).notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    description: text("description").notNull(),
    status: revenueOpportunityStatusEnum("status").notNull().default("OPEN"),
    severity: revenueOpportunitySeverityEnum("severity").notNull(),
    // 0-100 — see revenue.engine.ts SCORING_FORMULA doc.
    score: integer("score").notNull(),
    // 0-100 (percentage, kept as an integer — never a float — per project
    // money/number conventions).
    confidence: integer("confidence").notNull(),
    // Integer minor units (paise for INR), same convention as every other
    // money column in this schema. Can be 0 for opportunities where an
    // impact estimate isn't meaningful (should be rare).
    estimatedRevenueImpact: bigint("estimated_revenue_impact", { mode: "number" }).notNull(),
    currency: varchar("currency", { length: 3 }).notNull(),
    // Structured, machine-readable facts the score/description were
    // computed from — this is what the AI explanation layer is allowed to
    // read and cite. Never hand-edited; always written by the engine.
    evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull(),
    // What approving this opportunity would do — structured, not prose,
    // so the approval route can validate it before executing anything.
    recommendedAction: jsonb("recommended_action").$type<Record<string, unknown>>(),
    approvedBy: uuid("approved_by").references(() => users.id, { onDelete: "set null" }),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    rejectedReason: text("rejected_reason"),
    // --- Phase 7/8/9: bounded action execution (APPROVED -> EXECUTING -> EXECUTED|FAILED) ---
    // Who/when triggered execution (merchant-approved, never the AI directly — see
    // revenue.service.ts executeOpportunity). Structured, machine-readable outcome of
    // that execution — written ONLY by revenue.execution.ts, never hand-edited and
    // never generated by an LLM (same evidentiary rule as `evidence` above).
    executedBy: uuid("executed_by").references(() => users.id, { onDelete: "set null" }),
    executedAt: timestamp("executed_at", { withTimezone: true }),
    executionResult: jsonb("execution_result").$type<Record<string, unknown>>(),
    executionFailureReason: text("execution_failure_reason"),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    // The upsert target for re-running detection (see dedupeKey comment).
    orgDedupeUnique: uniqueIndex("revenue_opportunities_org_dedupe_unique").on(
      table.organizationId,
      table.dedupeKey
    ),
    orgIdx: index("revenue_opportunities_organization_id_idx").on(table.organizationId),
    orgStatusIdx: index("revenue_opportunities_org_status_idx").on(
      table.organizationId,
      table.status
    ),
    orgTypeIdx: index("revenue_opportunities_org_type_idx").on(table.organizationId, table.type),
    createdIdx: index("revenue_opportunities_created_idx").on(table.createdAt),
    scoreRange: check(
      "revenue_opportunities_score_range",
      sql`${table.score} >= 0 AND ${table.score} <= 100`
    ),
    confidenceRange: check(
      "revenue_opportunities_confidence_range",
      sql`${table.confidence} >= 0 AND ${table.confidence} <= 100`
    ),
    impactNonNegative: check(
      "revenue_opportunities_impact_non_negative",
      sql`${table.estimatedRevenueImpact} >= 0`
    ),
  })
);

export type RevenueOpportunity = typeof revenueOpportunities.$inferSelect;
export type NewRevenueOpportunity = typeof revenueOpportunities.$inferInsert;
export type RevenueOpportunityType = (typeof revenueOpportunityTypeEnum.enumValues)[number];
export type RevenueOpportunityStatus = (typeof revenueOpportunityStatusEnum.enumValues)[number];
export type RevenueOpportunitySeverity = (typeof revenueOpportunitySeverityEnum.enumValues)[number];
